@startuml

class SalesContract
class SalesOrder
class SalesOrderLine

interface Assignment

class EmployeeAssignment
class SupplierAssignment

class LaborContract
class PurchaseOrder
class PurchaseOrderLine

SalesContract *-- SalesOrder
SalesOrder *-- Assignment
SalesOrder *-- SalesOrderLine

Assignment <|.. EmployeeAssignment
Assignment <|.. SupplierAssignment

EmployeeAssignment -- LaborContract
SupplierAssignment -- PurchaseOrder
LaborContract *-- PurchaseOrderLine
PurchaseOrder *-- PurchaseOrderLine

@enduml