@startuml

package "execute-assignment" as Q {
    [training-delivery] as TD
}

package "manage-employment" as ME {
    [talent-contract-management] AS TCM
    
    [talent-compensation-and-benefits-management] AS TCBM
    [talent-payrolling] AS TP
  
    TCM -- TCBM : consume / transer benefits and leave
    TCM -- TP : accrue salary
    TCM -- TD : processing traing debt
}

@enduml