@startuml


package "execute-assignment" as EA {
    [timesheet-management] as TSM
}

package "manage-employment" as ME {
    [talent-compensation-and-benefits-management] as TCBM

    [talent-contract-management] AS TCM
    [talent-payrolling] as TP


    TCBM -- TCM : get labor contract
    TCBM -- TP : accrue salary
    TCBM -- TSM : get period hours
}

@enduml