@startuml

actor consultant
actor client
actor supplier
actor talent

package manage-suppliers {
    [supplier-management] as SM
    
    [actions-plugin] <<action-management>> as AC #Red
    [user-task-management-plugin] <<user-task-management>> as UT #Red

    SM <- UT
    AC -> SM
}

package shared-services {
    [action-management] as AM #Red
    [user-task-management] as UTM #Red
    [output-management] as OM #Red
    [document-management] as DM #Red
    [content-management] as CONTENT #Red
    [brand-management] as BRAND #Red
}

package it-platform {
    [iam] #Red
    [supplier-portal] as SP #Red
    [talent-portal] as TP #Orange
    [client-portal] as CP #Red
    [consultant-cockpit] <<sales-force>> as CONC #Orange
}

UT <-- UTM : my tasks
AC <-- AM : my actions
SM --> OM : send email
SM --> CONTENT : get message
SM --> BRAND : get brand
SM --> DM : create document
SM --> iam : sign-in, register, authorize

CONC <-- consultant

UTM <-- CP #Red : my tasks
AM <-- CP #Red : my tasks

UTM <-- SP #Red : my tasks
AM <-- SP #Red : my tasks

UTM <-- TP #Red : my tasks
AM <-- TP #Red : my tasks

UTM <-- CONC #Red : my tasks
AM <-- CONC #Red : my actions

CP <-- client
SP <-- supplier
TP <-- talent

@enduml